# Use root/example as user/password credentials
version: '3.1'
services:
  mongodb:    
    image: mongo  
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodbdata:/data/db    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  mongo-express:
    image: mongo-express  
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - mongodbdata:/data/db    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    networks:
      - backend

  ### Prefect Database
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
     - backend
  
 
  streamlit:    
    build: .
    container_name: streamlit    
    volumes:
      - "./../../:/app/"    
    ports:
      - "8501:8501"
      - "5000:5000"   
      - "4200:4200"
    # command: bash -c "python cygnss-deployment/prefect-deploy.py && streamlit run cygnss-deployment/dashboard.py"
    command: bash -c "python cygnss-deployment/prefect-deploy.py && mlflow ui"
    depends_on:
    - mongodb
    networks:
      - backend


 ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2.6.8-python3.11    
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - database    
    networks:
      backend

 ## Prefect Agent

  agent:
    image: prefecthq/prefect:2.6.8-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "demo"]
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    depends_on:
      - orion    
    networks:
      backend
  

    
networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local

